version: "3.9"

services:
  web:
    build:
      context: web
    ports:
      - 3000:3000
    volumes:
      - ./web:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    command: yarn dev
    depends_on:
      - graphql
      - keycloak
    environment:
      NEXTAUTH_URL: http://localhost:3000

  db:
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword

  graphql:
    image: hasura/graphql-engine:v1.3.3.cli-migrations-v2
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
      - keycloak
    volumes:
      - ./graphql/migrations:/hasura-migrations
      - ./graphql/metadata:/hasura-metadata
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@db:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: admin
      HASURA_GRAPHQL_JWT_SECRET: |
        {
          "jwk_url": "http://keycloak:8080/auth/realms/news-app/protocol/openid-connect/certs",
          "issuer": "http://localhost:8090/auth/realms/news-app",
          "claims_map": {
            "x-hasura-allowed-roles": ["user"],
            "x-hasura-default-role": "user",
            "x-hasura-user-id": { "path": "$$.user_id" }
          }
        }

  keycloak_db:
    image: postgres
    restart: always
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  keycloak:
    build:
      context: auth
    restart: always
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak_db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 8090:8080
    depends_on:
      - keycloak_db

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - db
      - keycloak_db
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin

volumes:
  db_data:
  keycloak_db_data:
